# Generated by Django 3.2.16 on 2023-01-09 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(blank=True)),
                ('booked_date', models.DateField()),
                ('booked_time', models.TimeField(choices=[('11.00', '11.00'), ('11.30', '11.30'), ('12.00', '12.00'), ('12.30', '12.30'), ('13.00', '13.00'), ('13.30', '13.30'), ('14.00', '14.00'), ('14.30', '14.30'), ('15.00', '15.00'), ('15.30', '15.30'), ('16.00', '16.00'), ('16.30', '16.30'), ('17.00', '17.00'), ('17.30', '17.30'), ('18.00', '18.00'), ('18.30', '18.30'), ('19.00', '19.00'), ('19.30', '19.30'), ('20.00', '20.00'), ('20.30', '20.30'), ('21.00', '21.00'), ('21.30', '21.30'), ('22.00', '22.00'), ('22.30', '22.30')], default='19.30')),
                ('number_guest', models.PositiveIntegerField(choices=[('3', '3'), ('1', '1'), ('6', '6'), ('5', '5'), ('4', '4'), ('7', '7'), ('2', '2')], default='2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_date'],
            },
        ),
    ]
