# Generated by Django 3.2.16 on 2023-01-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'declined')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('3', '3'), ('6', '6'), ('2', '2'), ('7', '7'), ('5', '5'), ('4', '4')], default='2'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
