# Generated by Django 3.2.16 on 2023-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230109_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[('4', '4'), ('2', '2'), ('5', '5'), ('1', '1'), ('6', '6'), ('3', '3'), ('7', '7')], default='2'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
