# Generated by Django 3.2.16 on 2023-01-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230109_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_time',
            field=models.CharField(choices=[('11.00', '11.00'), ('11.30', '11.30'), ('12.00', '12.00'), ('12.30', '12.30'), ('13.00', '13.00'), ('13.30', '13.30'), ('14.00', '14.00'), ('14.30', '14.30'), ('15.00', '15.00'), ('15.30', '15.30'), ('16.00', '16.00'), ('16.30', '16.30'), ('17.00', '17.00'), ('17.30', '17.30'), ('18.00', '18.00'), ('18.30', '18.30'), ('19.00', '19.00'), ('19.30', '19.30'), ('20.00', '20.00'), ('20.30', '20.30'), ('21.00', '21.00'), ('21.30', '21.30'), ('22.00', '22.00'), ('22.30', '22.30')], default='19:30', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[(2, '2'), ('4', '4'), (1, '1'), ('6', '6'), ('5', 5), ('3', '3'), ('7', '7')], default=2),
        ),
    ]
