# Generated by Django 3.2.16 on 2023-01-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230110_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[(7, '7'), (1, '1'), (3, '3'), (4, '4'), (6, '6'), (2, '2'), (5, '5')], default=2),
        ),
    ]
