# Generated by Django 3.2.16 on 2023-01-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20230110_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[(2, '2'), (5, '5'), (4, '4'), (7, '7'), (1, '1'), (3, '3'), (6, '6')], default=2),
        ),
    ]
