# Generated by Django 3.2.16 on 2023-01-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_number_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[('7', '7'), ('6', '6'), ('2', '2'), ('4', '4'), ('5', '5'), ('1', '1'), ('3', '3')], default=2),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('booked_date', 'booked_time'), name='unique_booking'),
        ),
    ]
