# Generated by Django 3.2.16 on 2023-01-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20230118_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('3', '3'), ('7', '7'), ('6', '6'), ('4', '4'), ('5', '5'), ('2', '2')], default=2),
        ),
    ]
