# Generated by Django 3.2.16 on 2023-01-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_number_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guest',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=2),
        ),
    ]
