# Generated by Django 3.2.16 on 2023-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20230120_0610'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('booked_date', 'booked_time', 'name'), include=('name',), name='unique_booking'),
        ),
    ]
